# Generated by Django 6.1.1 on 2026-09-25 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('A', 'Andamento'), ('N', 'Negado'), ('AP', 'Aprovado')], default='A', max_length=2)),
                ('descricao', models.TextField()),
                ('data_inscricao', models.DateField()),
                ('data_prazo', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
