# Generated by Django 6.1.1 on 2026-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('A', 'Andamento'), ('N', 'Negado'), ('AP', 'Aprovado')], default='A', max_length=2)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
