# Generated by Django 6.1.1 on 2026-09-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_data_inscricao'),
        ('vagas', '0002_vaga_data_iscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
